spring:
  application:
    name: resturant
  # Oracle Database Configuration
  datasource :
    driver-class-name : oracle.jdbc.OracleDriver
    username : hr
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
  messages :
    basename : i18n/messages
    local-default :
  # JPA and Hibernate Configuration for Oracle
  jpa :
    hibernate.ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
server:
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: always


key-config:
  key: cnjshfbuvgtryu43u8iodfhbvjygi3ruojfw
  dur: 1h

